### ISSUE TITLE
Screenshots and images are not shown in this CHM file on Win10

### ISSUE THREAD

**Issue by roslov** [blacksmoke26/Yii2-Manual-CHM#3]
I’m using Windows 10.
And screenshots and images are not shown in this CHM file.
I tried something like `Unblock-File -Path yii2-2.0.12-manual-2017-07-17.chm` from PowerShell, but it did not work for me.

**Comment by blacksmoke26** [comment]
I haven't tested CHM files on Windows 10, Will install on VMWare and Test the file,

In meantime the solution maybe there:
https://social.technet.microsoft.com/Forums/ie/en-US/aac9e3e3-7f57-42e4-b291-7fb1ed5baf8f/html-help-viewer-does-not-show-the-content-of-chm-file-right-pane-is-white-blank?forum=w7itproinstall

https://www.helpsmith.com/chm-cannot-be-displayed.php

**Comment by blacksmoke26** [comment]
Just tested on Windows 10 (x64)

CHM is ok.

Steps:
1. Download zip file from issue link.
2. Extracted zip and opened CHM (also unblocked)

Reference:
![image-screenshot](https://user-images.githubusercontent.com/425744/28387912-529fc6a2-6cea-11e7-9bd3-0343ce31aa52.png)

> You may not be able to see contents of a CHM that you open over a UNC path. If that is the case copy the file to a local drive.

**Comment by roslov** [comment]
This page also works for me.

But try other ones. For example, `Extentions API / shell`:

![](http://joxi.ru/ZrJ7RMf1nlDkmj?d=1)

**Comment by blacksmoke26** [comment]
opening CHM page url in IE display an ActiveX warning:
![bug](https://user-images.githubusercontent.com/425744/28427649-526c5816-6d90-11e7-8be4-9095397d20d0.jpg)

It seems CHM isn't able to get full access for non-local URLs. Will find some solution, hope it will be sorted

**Comment by blacksmoke26** [comment]
About the screenshot issue, looks like missing images or wrong url (local image) in manual, I am marking this issue as a 'BUG', I will fix it in next release.

@roslov Thank you!  Please report about more bugs if you can. It will improve the Manual.
