### ISSUE TITLE
New release for Yii 2.0.32

### ISSUE THREAD

**Issue by lourdas** [blacksmoke26/Yii2-Manual-CHM#8]
Hi,

It's been more than 2 months since the last chm release in that time, new releases of Yii and extensions have been released. It'd be nice to have a newer chm.

Thank you!

**Comment by blacksmoke26** [comment]
@lourdas  Yeah sure! Will do it ASAP!

**Comment by lourdas** [comment]
Ping....

**Comment by blacksmoke26** [comment]
Sorry for the delay. Published!
